### ISSUE TITLE
Tidak bisa redirect langsung ke peramban

### ISSUE THREAD

**Issue by apriliyanto** [DaleGia/ESPCaptiveImagePortal#2]
hallo sy Apriliyanto,,, telah mencoba proyek ini namun tidak otomatis buka ke gambar.
Harus memasukkan dl url 192.168.4.1

**Comment by DaleGia** [comment]
Hi @apriliyanto, 

Ill just leave a google translated version or your issue here.

"hello sy Apriliyanto ,,, have tried this project but it does not automatically open to images.
 Must enter dl url 192.168.4.1"

Sometimes the automatic redirection fails on particular browsers or operating systems. There is little that can done about this.

This project was specifically tested on chrome and Firefox browsers on an android device and worked well. You might have trouble with safari and iphones.
